### ISSUE TITLE
Doesn't work with 2.1.20

### ISSUE THREAD

**Issue by rishifter** [khonkhortisan/Answer-Button-Sounds#1]
No sound plays at all.

**Comment by khonkhortisan** [comment]
If I `raise ValueError('ease == 3 play called')` right after the play() it makes the sound once, it's broken because clearAudioQueue() moved from Review.nextCard so it could still be called.
(A workaround would be to, every card, re-register the hook, error out to delete the hook and play the sound, and make the user close the error pop-up.)

**Comment by khonkhortisan** [comment]
AKA avplayer.stop_and_clear_queue() which is called from 
[irrelevant] qt/aqt/addcards.py AddCard._addCards AddCards._reject
qt/aqt/sound.py AVPlayer.stop_and_clear_queue AVPlayer.shutdown clearAudioQueue
[irrelevant] qt/aqt/overview.py Overview.show
[irrelevant] qt/aqt/deckbrowser.py DeckBrowswer.show
qt/aqt/clayout.py CardLayout.reject
...
This all has something to do with
Tools→Preferences→Basic→☑ Interrupt current audio when answering. Disabling that makes the sound work if there's nothing already playing when you answer. [I had clearAudioQueue commented out at the time of writing this]
So the same as when I first wrote this: I need to interrupt the audio myself, and tell Anki not to. Or play it on another thread.

**Comment by khonkhortisan** [comment]
AVPlayer.play_tags gets called on the front and back of the card, and I want to disable interrupt_current_audio on the front of the card so my sound plays, but leave it at the user setting for the back of the card so this addon doesn't have side effects. 😕

**Comment by khonkhortisan** [comment]
Uploaded a version that plays sounds but leaks front side audio to the back side. https://github.com/khonkhortisan/Answer-Button-Sounds/commit/383abafad06ab96ecfdde543e278ae952e639d80

**Comment by Duytrungnuce** [comment]
Vere helpful, but not working in Version 2.1.20 (47a1bf8b)

**Comment by 75462565374252** [comment]
Anxiously waiting for this to be fixed. I need my review sounds. Thanks.

**Comment by 75462565374252** [comment]
> Uploaded a version that plays sounds but leaks front side audio to the back side. [383abaf](https://github.com/khonkhortisan/Answer-Button-Sounds/commit/383abafad06ab96ecfdde543e278ae952e639d80)

Can't get this to work either. So sad

**Comment by 75462565374252** [comment]
Anki 2.1.21 changelog:

> Fixed error messages when playing audio.
> Display a more useful message when mpv/mplayer not installed.
> Fixed interrupting of current audio when autoplay is turned off.

Add-on is still not working for me. Regular version plays no sound; version linked in previous post gives me:

> When loading 'Answer Button Sounds':
> Traceback (most recent call last):
>   File "aqt/addons.py", line 205, in loadAddons
>   File "/Users/jonas/Library/Application Support/Anki2/addons21/679615590/__init__.py", line 32, in <module>
>     if LetSoundBleedOntoNextCard_InsteadOf_CancelingSoundEffectSometimes:
> NameError: name 'LetSoundBleedOntoNextCard_InsteadOf_CancelingSoundEffectSometimes' is not defined

**Comment by rishifter** [comment]
It works for me after checking "Interrupt current audio when answering" but after doing 100-150 reviews it stops for no reason.

**Comment by ghost** [comment]
@khonkhortisan [Hitmarkers](https://ankiweb.net/shared/info/1776869150) seems to implement the audio correctly.
